### PR TITLE
Select Nodes for Latent/Images/Masks

### PR DESCRIPTION
**Pull request by Kosinkadink**
- Added Select Latents/Images/Masks nodes
- Reorganized some nodes in the menu
- Renamed 'Duplicate X Batches' to 'Repeat X' nodes
- Removed 'Batches' from Latent/Image/Masks node names
- Made almost all Latent nodes (besides Merge) properly account for other tensor props that may exist on the latents dict; Merge Latents node will require more time on my part to properly handle cases where props may exist on one passed in latent dict but not the other, etc.

### CODE REVIEW

**Comment by Quasimondo** [comment]
I have the strange issue that the "latents" input dot does not appear on the VHS combine video node, whereas the "VAE" pin does show up. When I look at the source code in custom_nodes I can see that is part of the "optional" inputs.  I also tried restarting or resizing the node, but no success. Any idea what could be the reason?

**Comment by AustinMroz** [comment]
The latent input is hidden until a vae is attached. 

https://github.com/user-attachments/assets/446b7b07-8e80-44f7-9191-1f5b316aedee

**Comment by Quasimondo** [comment]
Oh yes I see - thanks for the pointer! Whilst this is a clever approach I am not sure if I find it that useful, since it is not self-explanatory and requires people to know that instead of an image they can also use latents. And the part where the connection gets dropped if I remove the vae might also lead to involuntary errors.

**Comment by AustinMroz** [comment]
This sounds like a misunderstanding of the purpose. The functionality was primarily added for memory optimization and any quality of life it provides is entirely secondary. I am confident it would cause significantly more issues if the user was allowed to freely make connections.
- Users can't use a latent input or output without attaching a vae. Detecting if an output is used CAN NOT be done without breaking node output caching.
- Users shouldn't use a vae input when using image input or output. Since there's no current indication that a node indication is optional. There is no way to convey that a vae doesn't always need to be connected.
- Users can not use both image and latent options at the same time. While one of the inputs can be silently ignored on Video Combine. Node caching makes both impossible to detect and entirely self-defeating to implement on Load Video.

That said, improved documentation in-node documentation to better explain stuff like this is planned.

**Comment by Quasimondo** [comment]
First of all I think it is great to have the VAE encoder now directly in the there so I have no complaints about that. In the end I guess it is a matter of personal preferences - I prefer to see all my options and potentially get a warning if I use an unsupported combination rather than not seeing an option at all. So yeah my preference would be - have all input pins available, if latent + vae + images are present use latent, otherwise use image.

**Pull request merged**
