### PR TITLE
Add automatic ffmpeg downloading

### PR DESCRIPTION
**Pull request by Fannovel16**

### CODE REVIEW

**Comment by AustinMroz** [comment]
A system for bundled ffmpeg as a dependency is something I've been meaning to look into and I'm thrilled to see the implementation is so straightforward.

I want to take some time to think things over and hear from @Kosinkadink since it's adding a dependency, but my initial impression is that it's a great improvement.

**Comment by Kosinkadink** [comment]
Nice, that should help a lot with ffmpeg installation for peeps who are new to this.

By the way, why the change to how the video_formats folder is gotten? The existing solution was using ComfyUI's way of doing it, was there a problem on your end that you ran into?

**Comment by Fannovel16** [comment]
@Kosinkadink Yeah folder_paths.get_filename_list doesn't work on my machine. It throws a KeyError

**Comment by AustinMroz** [comment]
Oh... The 'video_formats' folder path was defined in AnimateDiff-Evolved, but I never implemented it here in VideoHelperSuite. Instead the existing definition leaks to the code that is run here since both of us still have AnimateDiff-Evolved enabled.  The definition just needs to be added somewhere, probably to nodes.py before the offending check is made.
```python
folder_paths.folder_names_and_paths["video_formats"] = (
    [
        os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "video_formats"),
    ],
    [".json"]
)

```

**Comment by Fannovel16** [comment]
@AustinMroz It works on my machine now. This PR is ready to be merged.

**Comment by Fannovel16** [comment]
> A system for bundled ffmpeg as a dependency is something I've been meaning to look into and I'm thrilled to see the implementation is so straightforward.

Imageio is goat.

> I want to take some time to think things over and hear from @Kosinkadink since it's adding a dependency
I can add some more code lines to download .whl file compatible with the system, decompress and get ffmpeg binary. But I think `imageio-ffmpeg` is already minimal and won't cause any conflict.

**Comment by AustinMroz** [comment]
I agree. This works great.

**Pull request merged**
