### PR TITLE
Add Load Video node

### PR DESCRIPTION
**Pull request by AustinMroz**
I'm opening this pull request early as an indicator of what I'm working on currently.

The python code for interfacing with ffmpeg to load a video as a series of frames is functional, but I'm planning to do a good bit of refactoring on the javascript side in order to
- Allow uploading of videos from the webui
- Generalize the video preview code to also work for the new Load Video node
- Implement the requested functionality for pausing/hiding video previews
- (hopefully,)  display a still image preview in the format designated in webui settings when the video preview is set to paused.

### CODE REVIEW

**Comment by Kosinkadink** [comment]
Sweet, good idea. I'll do the same once I start working on the latent/image splitting/combining nodes. As soon as you ahve the nodes ready, we can start using them in the AnimateDiff repo samples and mention it in the README. And we can ask Comfy Manager repo to add this to their list.

**Comment by Kosinkadink** [comment]
Even if you can get a rudimentary "Load Video" node to work without previous, I think that would warrant merging to main so that it's there for use.

**Comment by AustinMroz** [comment]
I'll continue to work on the js side, but in its current state, the Load Video node has the bare minimum settings I think are required to make it useful for end users and worth merging.

In addition to the above concerns of previews and uploading
- It's not currently well communicated that leaving force_rate at the default value of 0 disables it.
- There's no warnings or sanity checks to prevent users from trying to use a large video

**Comment by Kosinkadink** [comment]
@AustinMroz Hey, sorry I didn't have a chance to look at this, I was still recovering from my all nighter on motion loras. I think overall it looks great, but just wanna chime in and say that we actually can consider using other python libraries to do stuff.

We can make a requirements.txt file, and use opencv (cv2) to do some video work too if needed. When we submit repo to comfy manager, we can set the installation setting there to use the requirements, so that if comfy manager is used to install it, it will "automatically" run the requirements.txt install call. And for manual install we can put in the readme to run requirements.txt in venv.

I don't know if there is any different between the resulting quality when using opencv to open a video stream, but it might make our lives infinitely simpler for debugging (and usability) if we only use ffmpeg stuff when absolutely required.

**Comment by AustinMroz** [comment]
No worries. The motion lora stuff looks super cool and I would hate to have distracted you from implementing it.

I'm aware that requirements can be added, but I don't have experience with using opencv and it seems like a particularly heavy dependency for saving about 10 lines of codes when ffmpeg is already required for the combine node.

As for quality, ffmpeg is honestly state of the art and, as best I can tell, both opencv and torchaudio already use ffmpeg in their backend implementations. Given I am more familiar with interacting with ffmpeg directly, the documentation on utilizing ffmpeg seems more available, and that advanced configuration can be better exposed to the end user, I think an implementation that utilizes ffmpeg directly is preferable.

At the same, I would like to work towards an implementation that doesn't fail if system ffmpeg is unavailable and will continue to ponder the issue.

**Comment by Kosinkadink** [comment]
Gotcha. I have a lot of opencv experience, I can throw in some code for fallback in Load Videos node in case ffmpeg is not installed, if you're fine with us introducing opencv. I don't think there is a simpler way of implementing loading frames for videos directly in python, so that might be the route we need to take for ffmpeg fallbacks. I'll put the code in a PR, so that you can take a look and make any changes as needed.

**Pull request merged**
