### PR TITLE
CV LoadVideo + other small things

### PR DESCRIPTION
**Pull request by Kosinkadink**
Changed LoadVideo node to use cv to support frame_load_cap and skip_first_frames + additional formats, added frame_count output, changed visual appearance of nodes to make it clear what custom nodes they are part of.

If some things in ffmpeg are harder to figure out at the moment, we might go ahead and make Load Video node use opencv for all its functionality. I made it support loading only a certain amount of frames and skipping a certain amount of frames. I also output a frame_count so that it can be passed to nodes that will care about the number of images loaded.

Force_size currently does nothing in this code. If we want to make that work later, we could remove it as a parameter for now and add it back at a later date. I kind of want to start adding the image/latent nodes and then reference this repo in AnimateDiff, so getting this bare amount of functionality will be enough to get peeps going, I think. I want to know what you think about going this route.

### CODE REVIEW

**Comment by Kosinkadink** [comment]
The biggest features peeps seem to be wanting for AnimateDiff is loading a video as images, as well as being able to split/combine image/latent batches. I'm going to knock out the image/latent splitting tonight in a separate PR, and then hopefully we can have this Load Video node working to a minimum. I'll try to get the force_size funtionality working, as well.

**Comment by AustinMroz** [comment]
The methodology looks fine and I agree it's good to merge. Since there is demand for it, I think it's good to move quickly and make it available for people to use.

skip_first_frames and frame_load_cap can be implemented in the exact same way for ffmpeg and only get finicky if you want consistant behaviour across changes in frame rate. I do think it's valuable to keep the setting for frame rate, but I can just reimplement this for opencv in a new pull request. Resizing can probably be implemented as well by calling the associated function from the existing image resize node on individual frames. Though we could just expect users to resize the images themself, I think it provides valuable quality of life to automatically resize the input frames to the resolution that works best with AnimateDiff.

**Comment by AustinMroz** [comment]
Maybe I spoke too soon. I'm getting a number of errors with the opencv code now that I'm testing it.
- It tries to use hardware decoding for av1, and fails since it's not supported on  my machine
- np.float is deprecated and throws an error for me.

**Comment by Kosinkadink** [comment]
The np.float is a typo, was moving the code to a diff place and I accidentally left out the "32" from float32. Interesting about the av1 decoding though

**Comment by AustinMroz** [comment]
I've pushed a number of improvements to loadvideo_improvements which 
- Implement force_rate and force_size in opencv
- Implement skip_first_frames and frame_load_cap in ffmpeg
- Force resizing to be a multiple of 8
- Sets ffmpeg back to being the default, but also surrounds the actual executions in try blocks and retries the loading with the opencv code if an error occurs.

**Comment by Kosinkadink** [comment]
Sweet, sounds good. One thing I have a question about though while I looked through your changes, does the skip_first_frames still work in the opencv fallback code? It looks like total_frame_count incrementing was deleted there.

**Comment by AustinMroz** [comment]
Total frame count was moved closer to where the a frame is obtained form opencv so that the total_frame_count determines the same start frame regardless of frame rate override.

Upon further consideration, it's probably better to count the frames after frame rate overrides. This makes changing the frame rate inconvenient, but lets you actually use math nodes and the output frame count to automate inrementing the start frame.

**Comment by Kosinkadink** [comment]
If you feel good about your changes in that other branch, feel free to merge it into this one

**Comment by Kosinkadink** [comment]
Another thing we might consider changing is that if we can't get an "upload video" button, we could instead go this route and not require any usage of the input directory. Where, the full path of the input file can be pasted in, and then the file won't need to be copied or anything, plus the user can have it anywhere on their computer/whatever container they are using to run Comfy: 
image

In the case of this Load Images node in the image, the path has to be to a dir.

**Comment by AustinMroz** [comment]
The upload button alone should be easy and I'll quickly add it. The hard part is me getting feature crept into wanting to inject a new endpoint into the server that will re-render previews/frames on the fly.

I'd be particularly concerned with the text box approach since it seems like a major security vulnerability for anyone not running the plugins localy to allow arbitrary file access.

**Comment by Kosinkadink** [comment]
Hmm, interesting point about the text box approach. Although, personally, I find comfy nearly unusable with the input folder system it has - with nearly every other tool, I can easily specify any directory or file I want to process, but then with comfy everything gets copied to the input folder, and everything just gets gunked up in input directory very quick. I think my holdup with this can be solved if we implement auto creation of folders for our nodes. And using subfolders in the input folder - otherwise, imo we will be dead in the water for saving and loading image sequences.

**Comment by Kosinkadink** [comment]
We can rework the Load Images node, too, to have a button to "Upload Directory" or something, so that a whole folder can get uploaded.

**Comment by AustinMroz** [comment]
I'll probably have to look into that tomorrow. I vaguely recall that web browsers didn't support uploading folders.

**Comment by AustinMroz** [comment]
Having a config file would certainly be an improvement, but it looks like it might not be necessary after all.

It is possible to select entire folders with js. Assuming the existing file upload endpoint in the python code allows for folder creation, it shouldn't take me more than 15 minutes or so to implement.

**Pull request merged**
