### PR TITLE
JS rewrite (round 2)

### LINKED ISSUE #43: Load Video (Upload) node becomes uninteractable upon refresh (F5) or hard refresh (Ctrl+F5)
@AustinMroz hey, after merging into main, found an odd issue - if you add a Load Video (Upload) node (or more than 1), and refresh the page, they become seethrough and completely uninteractable unless the page is refreshed again:
image

I also performed a git pull after adding one of those nodes, and upon refreshing and reloading the page, I have a Load Video (Upload) node that is permanently stuck as uninteractable in my workflow. The previews and such still play while being uninteractable - no right clicking, no moving, etc, does anything, and comfy behaves as if the nodes aren't there.

### PR DESCRIPTION
**Pull request by AustinMroz**
Iterates upon #36 with a number of fixes
- Fixes #43, a race condition where the callback for loaded metadata fires before a draw operation has occurred.
- Ensure computeSize always returns a number greater than 0
- Fixes the mouse button being stuck down after an upload operation, which resulted in inadvertent changes to number fields
- Pausing or hiding previews is now tracked in the state of the preview widget
- When an execution is loaded from history, the correct output is restored instead of the output of the preceding execution.

### CODE REVIEW

**Comment by Kosinkadink** [comment]
Testing it locally atm, and so far so good. One question, I'm guessing gifs don't have the ability to be paused, which is why "Pause preview" is not available for gifs?

**Comment by AustinMroz** [comment]
Yep. I'm not happy with doing so as gifs are more likely to cause performance issues in my experience, but from my searching there wasn't an easy solution. Might be possible by swapping to the first frame png that is also saved, but that implementation seems involved and brittle.

**Comment by Kosinkadink** [comment]
Gotcha, in that case, totally fine to not allow pausing gifs. I did however find an issue with loading old workflows:

https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/assets/7365912/7414fc2f-a6d0-4174-9fd3-f91403cb96d5

Old Video Combine nodes on existing workflows that didn't use new version of VHS do not show the preview, but any new nodes placed work as expected.

**Comment by Kosinkadink** [comment]
After your latest commit, I tried out the txt2img workflow from https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved#txt2img, and I still get the issue of the Video Combine node from there not working, same as before. I tried it out in Chrome and Edge.

**Comment by AustinMroz** [comment]
I see.

I was mistaken in my understanding of how the preview information was stored in old workflows and only did checks on workflows which have not executed. I've not been able to test the linked workflow verbatim (which would take about 2 hours on my system) but my slight modification reproduced the described error and is functional now. Will continue testing to make sure this change didn't have side effects.

**Comment by Kosinkadink** [comment]
After doing a Ctrl+F5, old workflows have the Video Combine nodes working as intended. I was doing a workflow-by-workflow check to see if anything that used VHS nodes broke at all, and the only thing that currently needs to be manually tweaked taht I saw was the Load Images (Upload) node:
image
workflow: https://github.com/Kosinkadink/ComfyUI-AnimateDiff-Evolved#txt2img-w-initial-controlnet-input-using-normal-lineart-preprocessor-on-first-txt2img-as-an-example

image_load_cap does not get a value, and all values afterwards are instead shifted one slot down. Not sure if there is anything we can do about that, worst case we accept that some workflows will break and will have to be manually readjusted.

Also, a quick way to test out the VHS nodes on those workflows is to skip the AnimateDiff Loader node and link raw model to the KSampler, and/or setting the batch_size to 1.

**Comment by AustinMroz** [comment]
I've debated how robust or strict the conversion code should be given it would immediately become deprecated after release and the information to convert from is quite limited. Most of the existing check is just verifying the number of widgets to try and prevent future changes that add widgets from shifting things.

I'll push a change for Load images since it's reasonably likely to come up.

**Comment by Kosinkadink** [comment]
Gotcha, I think since that node had custom .js written for it, it might have been the only node left with a possible issue. I haven't found any further issues. If you can't think of anything else that should be added, we can merge the PR, and see what sorta reports we get.

**Comment by AustinMroz** [comment]
That matches my thoughts. I can't thank you enough for the assistance you've provided.

I'm continuing to work on the readme

**Comment by Kosinkadink** [comment]
No problem, and thank you for working on all the VideoHelperSuite features up till now! Let me know if you'd like to merge the changes in now, or wait until you have had a chance to work on the README. I'm fine either way.

**Comment by AustinMroz** [comment]
I think it's good to merge.

**Pull request merged**
