### PR TITLE
UploadVideo, gif preview autoplay fix, VideoInfo out from LoadVideo, …

### PR DESCRIPTION
**Pull request by JaredTherriault**
…support webp, apng, mjpeg

-Add PIL fallback to LoadVideo to support video types not supported by opencv2, such as webp, apng, and mjpeg. Changing frame rate is not supported in this mode. The output log will inform you of this when the fallback is used. 
-Added a video_info output to LoadVideo which includes more information, such as the frame count, fps, duration and frame time for the input video and the output frames 
-Added a new node UploadVideo which includes the functionality of LoadVideoUpload insofar as copying a video to the input folder but also allows the user to upload to temp instead for testing so as not to clutter the input folder. Uploaded videos now go to a subfolder, 'VHS_upload'. 
-Added gif preview to UploadVideo so uploaded videos can be viewed on the node when selected. 
-Fixed autoplay for gif preview on VideoCombine, still not working for videos on UploadVideo node. 
-Added drag and drop for videos on UploadVideo node. 
-Changed 'force_frame_rate' to 'desired_frame_rate' because it cannot be forced in PIL fallback, this is an effort to communicate this to the user
-Bring LoadVideoUpload features up to parity with LoadVideoPath and UploadVideo
-Add guard clause for undefined video widget value

### CODE REVIEW

**Comment by Kosinkadink** [comment]
Hey, thanks for the PR! I only had a bit to look at it rn (busy working on some stuff for Advanced-ControlNet), but here are some things I think can be tweaked:

1) Keep the IDs for the correlating nodes the same - VHS_LoadVideoPath should stay as VHS_LoadVideoPath (but the name can change), and VHS_LoadVideoUpload should stay as VHS_LoadVideoUpload (but the name can change). This will make it so that when users update, their existing nodes won't just error out. Users might still need to tweak things on their end to make them work if new properties are added, but at least they will know the nodes still exist and they are less likely to open new Issues about nodes 'not existing anymore'.

2) For the Load Video-related nodes, keep an int output for the frame count in addition to the OutVideoInfo. For 99% of the use cases at the moment, the only things a user will make use of from these nodes is the actual images and the count of the loaded images to plug into something like Empty Latent Image node (when used for AnimateDiff). It would be good to keep these video nodes working the same (to not break current workflows) and not add an extra node to be required to make use of that feature. I know it's technically duplicate info since it's already in OutVideoInfo, but I want to avoid an 'over-nodification' for basic features - having the extra OutVideoInfo is a great addition though.

3) For OutVideoInfo, I would suggest changing the naming from 'input' and 'effective' to something like 'original' and 'actual'. The worst case we want to avoid is a user being confused about which values are from the original video (with is kind of 'extra') and which is the stuff that actually correlates to what is usable with the loaded frames in ComfyUI.

**Comment by JaredTherriault** [comment]
@Kosinkadink thank you for the feedback Kos, I have updated the PR with your recommendations and went ahead and updated LoadVideoUpload to parity with the other updated nodes from this PR.

**Comment by Kosinkadink** [comment]
Thanks! I'll take a look later today.

**Comment by Kosinkadink** [comment]
Looks good, merging (and will do some edits afterwards).

**Pull request merged**
