### PR TITLE
In Video Combine, capture stderr from ffmpeg

### PR DESCRIPTION
**Pull request by AustinMroz**
This ensures the error pop up in the webui contains information on what went wrong with two minor caveats:

The error output of ffmpeg is no longer colored. This could be re-enabled with an environment variable, but it would then need to be manually filtered out from the webui display.

This introduces a likely insignificant chance of deadlock. If stderr somehow becomes full without ffmpeg terminating, it could block execution of writing data to stdin. I don't forsee a situation where this could occur as ffmpeg is set to low verbosity.
image

### CODE REVIEW

**Comment by Kosinkadink** [comment]
I think this is definitely a useful change, will help us debug stuff other than getting a 'Broken pipe' as the error. Is there a way to add a timeout to the proc read and wait calls to avoid the change of deadlock you mentioned? If not, should not be too big of a deal, and we'll definitely hear about if it ever happened haha.

Also, I suppose this is unrelated to this PR, but I think to avoid a 'metadata failed to be added, resulting in Broken pipe and no video saved' problem https://github.com/Kosinkadink/ComfyUI-VideoHelperSuite/issues/72, we should also add some logic to retry the ffmpeg call without the metadata added into the comment if save_metadata is true and there was a broken pipe.

**Comment by AustinMroz** [comment]
A timeout can be provided for the wait call, but my conceptual understanding is that this could only occur at the earlier calls to sys.stdin.write and I do not see a way to see a way to provide a timeout to sys.stdin.write. There would be a solution with swapping to subprocess.run if frames can be accessed as a single contiguous array.

A fallback for metadata as described would be fairly simple to implement. I'll plan to push a commit here that solves both these issues.

**Comment by AustinMroz** [comment]
I've made the suggested changes and done my usual line of tests (including the reboot to windows).

**Comment by Kosinkadink** [comment]
Sweet, I'll merge this in. If we get a lot of error reports while it's in the wild, I'll revert it so we can fix the errors, but the code looks fine to me.

**Pull request merged**
